#!/usr/bin/env bash

# Installing Nginx on my web-01
# curl, it must return a page that contains the string Hello World!
# Nginx should be listening on port 80

apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
ufw allow 'Nginx HTTP'
service nginx restart
