#!/usr/bin/env bash

# Installing Nginx on my web-01
# curl, it must return a page that contains the string Hello World!
# Nginx should be listening on port 80
# Configure your Nginx server so that /redirect_me is redirecting to another page.

apt-get -y update 
apt-get -y upgrade 
apt-get -y install nginx 
echo "Hello World!" > /var/www/html/index.nginx-debian.html
ufw allow 'Nginx HTTP'
sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}' /etc/nginx/sites-available/default
service nginx reload
