#!/usr/bin/env bash
# Installing Nginx on my web-01
# curl, it must return a page that contains the string Hello World!
# Nginx should be listening on port 80
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get -y update 
sudo apt-get -y upgrade 
sudo apt-get -y install nginx 
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo ufw allow 'Nginx HTTP'
if ! grep -q "location \/redirect_me {" /etc/nginx/sites-available/default; then
    sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}' /etc/nginx/sites-available/default
fi
sudo service nginx reload
