#!/usr/bin/env bash
# Installing Nginx on my web-01
# curl, it must return a page that contains the string Hello World!
# Nginx should be listening on port 80
# Configure your Nginx server so that /redirect_me is redirecting to another page.

apt-get -y update 
apt-get -y upgrade 
apt-get -y install nginx 
echo "Hello World!" > /var/www/html/index.nginx-debian.html
ufw allow 'Nginx HTTP'
# Check if the location block already exists before adding it
if ! grep -q "location \/redirect_me {" /etc/nginx/sites-available/default; then
    sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}' /etc/nginx/sites-available/default
fi

# Check if the custom_404.html location block already exists before adding it
if ! grep -q "location = \/custom_404.html {" /etc/nginx/sites-available/default; then
    sed -i '/^}$/i \ \n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t\treturn 404 "Ceci n'\''est pas une page";\n\t}' "/etc/nginx/sites-available/default"
fi

service nginx reload
