#!/usr/bin/env bash
# setup a firewall

# Install ufw
sudo apt-get -y update 
sudo apt-get -y install ufw

# block incoming traffic
sudo ufw default deny incoming

# allow incoming traffic on ports 22 80 443
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80

# start ufw
sudo ufw enable -y
