#!/usr/bin/env bash
# Run Nginx as Nginx User

# stop apache2
sudo pkill apache2

# Configure Nginx to run as nginx user and listen on port 8080

sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# change config file permission
chmod 644 /etc/nginx/nginx.conf
# start nginx
sudo -u nginx service nginx start 
